version: '1'
services:
  nginx-react:
    image: reactapp:latest
    container_name: stc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 80:80
    environment:
      NODE_ENV: production